#服务器端口
server:
  port: 8080
  context-path: /manage

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.100.83:3306/pls?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: XVQ8GfSFd8YIc+wdjvT91b4cPdct2RycUXnKW6SqMZKXAlCtBBDoVotZ5+NMLAsKaXMrzPzNgHiujNHq681/Lw==
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 初始化大小，最小，最大
    initialSize: 20
    minIdle: 1
    #maxIdle: 50  deprecated
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  #文件上传配置
file:
  upload:
    max-size: 10000000
    path: uploadfiles